---
index: true
meta: 
  title: Daffodil Digital
  description: Helping brands tell their stories in smarter ways
  keywords: agency, social, social media, digital, digital marketing, marketing, strategy, storytellers, teachers
  image: '/img/logo.jpeg' 
sections: 
  - guide
