---
url: http://www.daffodildigital.com/
title: Daffodil Digital
description: Helping brands tell their stories in smarter ways
keywords: agency, social media, digital marketing, content strategy, marketing, strategy, storytellers, teachers
image: 'img/logo.jpeg'
social:
  instagram: https://instagram.com/daffodildigital/
  twitter: https://www.twitter.com/daffodildigital/
  facebook: https://www.facebook.com/daffodildigital/
